### ISSUE TITLE
bcdb: only created required namespace in zdb

### ISSUE THREAD

**Issue by zaibon** [rivine/recordchain#51]
At the moment it seems that every object define in a schema result in a table in bcd and in a namespace in zdb.

But in my case, I define some objects cause I use them inside another object. like so :
```toml

@url = zrobot.task
@name = task
guid        = ''    (S)
action_name = ''    (S)
args        = {}    (dict)
state       = ''    (S)
eco         = ''    (S)
created     =       (D)

@url = zrobot.service.info
@name = info
template    = ''    (S)
version     = ''    (S)
name        = ''    (S)
guid        = ''    (S)
public      = false (B)

@url = zrobot.service
@name = service
info    =      (O) !zrobot.service.info
states  = {}   (dict)
data    = {}   (dict)
tasks   =      (LO) !zrobot.task
```

So here, the only object that I'm going to ever save is ` zrobot.service`. Task and info will never be saved alone.
Is there a way to specify that task and info object should not result in a table and are just sub object of the service object ?
